version: '3.8'

services:
  mongodb:
    image: mongo:4.4.18
    container_name: db-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - internal-network
    restart: unless-stopped

volumes:
  mongo-data:

networks:
  internal-network:
    external: true