services:
  registration:
    build: .
    container_name: ${PRJ_NAME}-register
#    image: ${PRJ_NAME}-image
    volumes:
      - ./app:/app
    environment:
      - PRJ_NAME
      - CONFIG_DIR
      - PORT
    networks:
      - internal-network

  mongodb:
    container_name: ${PRJ_NAME}
    image: mongo:4.4.18
    ports:
      - ${PORT}:${PORT}
    volumes:
      - mongo-data:/data/db
    networks:
      - internal-network
    restart: unless-stopped

volumes:
  mongo-data:

networks:
  internal-network:
    external: true